name: kosiservice
description: "Kosi Service is an all-in-one app that connects you with local service providers including cleaners, electricians, plumbers, drivers, wall painters, and carpenters. With just a few taps on your smartphone, you can find and hire trustworthy service providers to help you with your home or office needs"

publish_to: 'Kosi service'


version: 1.11.0+11

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_database: ^10.2.3
  firebase_auth: ^4.7.3
  clipboard: ^0.1.3
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  universal_html: ^2.0.0
  lottie: ^2.4.0
  fluttertoast: ^8.0.7
  url_launcher: ^6.1.12
  geolocator: ^10.0.0
  sliding_sheet: ^0.5.2
  share: ^2.0.4
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  android_id: ^0.3.5
  pdf: ^3.6.1
  order_tracker_zen: ^1.0.0+4
  path_provider: ^2.0.3
  open_file: ^3.3.2
  cloud_firestore: ^4.9.1
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^14.7.1
  flutter_local_notifications: ^16.1.0
  flutter_carousel_widget: ^2.1.2
  video_player: ^2.8.1
  webview_flutter: ^4.4.4
  flutter_widget_from_html: ^0.14.11
  infinite_carousel: ^1.0.3
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  geocoding: ^2.1.1
  google_maps_flutter_web: ^0.5.4+3
  onesignal_flutter: ^5.0.4
  custom_rating_bar: ^2.0.5
  font_awesome_flutter: ^10.7.0
  flutter_speed_dial: ^7.0.0
  responsive_builder: ^0.7.0
  whatsapp_unilink: ^2.1.0
  firebase_analytics: ^10.8.5
  restart_app: ^1.2.1
  phonepe_payment_sdk: ^2.0.1
  crypto: ^3.0.3
  upi_india: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logofirst.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logofirst.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"


# For web-specific code, use the "web" section as a top-level entry
web:
  # Add any web-specific dependencies here
  dependencies:
    universal_html: ^2.0.0

  # Add any web-specific configurations here
  # Example: If you need to specify the output directory for web builds
  build:
    web:
      outputDirectory: build/web

flutter:
  # Other configurations...
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
    - family: PTSerif-Bold
      fonts:
        - asset: assets/fonts/PTSerif-Bold.ttf
    - family: AbrilFatface
      fonts:
        - asset: assets/fonts/AbrilFatface.ttf