// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBScD54azyQNpWJ03bQ8fX-NEOmWvqho4s',
    appId: '1:987733786476:web:fd03f93c768ed7f0273d49',
    messagingSenderId: '987733786476',
    projectId: 'firstandfast-781dd',
    authDomain: 'firstandfast-781dd.firebaseapp.com',
    databaseURL: 'https://firstandfast-781dd-default-rtdb.firebaseio.com',
    storageBucket: 'firstandfast-781dd.appspot.com',
    measurementId: 'G-VEVLPJJL1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABRWRZ3zQxhVrPl3LDSXTDMXTfJFVWpWs',
    appId: '1:987733786476:android:98bbbc8a818ec0db273d49',
    messagingSenderId: '987733786476',
    projectId: 'firstandfast-781dd',
    databaseURL: 'https://firstandfast-781dd-default-rtdb.firebaseio.com',
    storageBucket: 'firstandfast-781dd.appspot.com',
  );
}
